# Generated by Django 4.1 on 2024-04-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DANHSACH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xe',
            name='ngay_tao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
