# Generated by Django 4.1 on 2024-03-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DANHSACH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xe',
            name='bien_so',
            field=models.CharField(default='', max_length=250),
        ),
    ]
