# Generated by Django 4.1 on 2024-06-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DANHSACH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capnhat',
            name='trang_thai_sdtg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capnhat',
            name='trang_thai_sdtn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capnhat',
            name='trang_thai_tn',
            field=models.BooleanField(default=False),
        ),
    ]
